package error

type Project int

const (
	EMPTY_PROJECT_NAME        = 700
	EMPTY_PROJECT_DESCRIPTION = 701
	EMPTY_PROJECT_OWNER       = 703
	PROJECT_ALREADY_EXISTS    = 704
	PROJECT_NOT_DELETED       = 705
	PROJECT_NOT_FOUND         = 706
)
